# Question 1
## Write a Python Program to Add Two Matrices?

In [7]:
import numpy as np

a_mat=np.array([[1,2],[2,2]])
b_mat=np.array([[7,5],[1,6]])
a_mat+b_mat

array([[8, 7],
       [3, 8]])

# Question 2
## Write a Python Program to Multiply Two Matrices?

In [10]:
np.matmul(a_mat,b_mat)

array([[ 9, 17],
       [16, 22]])

# Question 3
## Write a Python Program to Transpose a Matrix?

In [13]:
b_mat

array([[7, 5],
       [1, 6]])

In [14]:
b_mat.transpose()

array([[7, 1],
       [5, 6]])

# Question 4
## Write a Python Program to Sort Words in Alphabetic Order?

In [22]:
words_list=['Write','a','Python','Program','to','Sort','Words','in','Alphabetic','Order']

In [26]:
words_list=[i.lower() for i in words_list]
words_list.sort()
words_list

['a',
 'alphabetic',
 'in',
 'order',
 'program',
 'python',
 'sort',
 'to',
 'words',
 'write']

# Question 5
## Write a Python Program to Remove Punctuation From a String?

In [29]:
import re
 
string = "'Write','a','Python','Program','to','Sort','Words','in','Alphabetic','Order'"
 
print(f'The original string is :{string}')
 
res = re.sub(r'[^\w\s]', '', string)
res

The original string is :'Write','a','Python','Program','to','Sort','Words','in','Alphabetic','Order'


'WriteaPythonProgramtoSortWordsinAlphabeticOrder'